### ISSUE TITLE
getDisplayMedia api能否获取到4K的高清分辨率？

### ISSUE THREAD

**Issue by angular-v** [LiteAVSDK/TRTC_Web#16]
该sdk屏幕分享获取到的分辨率最大是1920p，输出视频质量低于实际电脑支持的最大分辨率，有没有办法提高输出的视频质量以获得高清分辨率视频？

**Comment by Rychou** [comment]
https://web.sdk.qcloud.com/trtc/webrtc/doc/zh-cn/LocalStream.html#setScreenProfile

可以用这个 api
