### ISSUE TITLE
trtc.startLocalVideo 中的参数 config.view 要求

### ISSUE THREAD

**Issue by yingdam** [LiteAVSDK/TRTC_Web#47]
使用v5版本。
trtc.startLocalVideo 中的参数 config.view 是否可以是HTMLVideoElement？

在 html 中设置 `<div id="local" style="position: absolute; width: 400px; height: 300px; right: 10px; top: 200px;"></div>` 
trtc.startLocalVideo({view: document.getElementById('local')}); 可以渲染出本地摄像头画面。

但是写为 `<video id="local" style="position: absolute; width: 400px; height: 300px; right: 10px; top: 200px;"></video>` 
trtc.startLocalVideo({view: document.getElementById('local')}); 就无法渲染出本地摄像头画面。

这是什么原因？

**Comment by Rychou** [comment]
建议使用 div 标签。SDK 会在 view 参数指定的标签下，创建 video 标签播放视频。

如果 view 使用 video 标签，则会出现如下情况：
```js
<video> // 您创建的  video 标签。
  <video></video> // 这个是 sdk 生成的 video 标签，浏览器不会渲染 video 标签内部的元素，因此 sdk 创建的 video 标签是看不到的。
</video>
```

**Comment by Rychou** [comment]
若您需要自定义采集和自定义渲染，可以参考这个文章：https://web.sdk.qcloud.com/trtc/webrtc/v5/doc/zh-cn/tutorial-20-advanced-customized-capture-rendering.html
