### ISSUE TITLE
直播流能区分客户端吗？

### ISSUE THREAD

**Issue by IndexLibrary** [LiteAVSDK/TRTC_Web#61]
目前在**stream-added**回调参数里看了下，只有**client_.basis_.os**比较像，但是windows跟安卓的推流这个字段都是**Windows**
sdk的版本是**4.15.0**

**Comment by Rychou** [comment]
是需要在拉流端检测推流端的 UA 信息吗？这个 SDK 没有提供这个能力的。可以借助业务侧信令通道或者 TIM SDK 做同步。

也可以通过 SEI 消息来实现：https://web.sdk.qcloud.com/trtc/webrtc/doc/zh-cn/Client.html#sendSEIMessage

**Comment by IndexLibrary** [comment]
> 是需要在拉流端检测推流端的 UA 信息吗？这个 SDK 没有提供这个能力的。可以借助业务侧信令通道或者 TIM SDK 做同步。
> 
> 也可以通过 SEI 消息来实现：https://web.sdk.qcloud.com/trtc/webrtc/doc/zh-cn/Client.html#sendSEIMessage

是的，可以了
