### ISSUE TITLE
5.x不支持辅流自定义采集

### ISSUE THREAD

**Issue by Wulawa** [LiteAVSDK/TRTC_Web#70]
一个实例同时推主流 + 辅流，辅流只能使用屏幕共享，应用场景太局限了，有没有计划调整

**Comment by Rychou** [comment]
你好，这块我们有规划的。

了解些信息，您的业务利用辅流推自定义采集是用于实现什么场景呢？

**Comment by Rychou** [comment]
```js
trtc.startScreenShare({ option: { videoTrack: MediaStreamTrck }});
```

你可以试试这样，目前可以通过这个参数自定义采集，文档中还未暴露这个参数。后续版本更新到文档中。

**Comment by Wulawa** [comment]
> 你好，这块我们有规划的。
> 
> 了解些信息，您的业务利用辅流推自定义采集是用于实现什么场景呢？

培训、会议等场景，摄像头是固定的，辅流用于共享屏幕，视频，文档等

**Comment by Rychou** [comment]
> > 你好，这块我们有规划的。
> > 了解些信息，您的业务利用辅流推自定义采集是用于实现什么场景呢？
> 
> 培训、会议等场景，摄像头是固定的，辅流用于共享屏幕，视频，文档等

好嘞，了解了，上面提到的方法能满足您的需求吗？
