### ISSUE TITLE
local暂停摄像头采集后恢复，remote无法恢复

### ISSUE THREAD

**Issue by JeffesJiang** [LiteAVSDK/TRTC_Web#82]

**Comment by Rychou** [comment]
@JeffesJiang  你好，请问是如何操作复现的呢？

可以提供一下 sdkAppId、roomId、userId、时间点，我排查一下。

**Comment by JeffesJiang** [comment]
> @JeffesJiang 你好，请问是如何操作复现的呢？
> 
> 可以提供一下 sdkAppId、roomId、userId、时间点，我排查一下。

roomid 使用过 7777 和 8888
sdkAppid 1600012148
userid 1和2 双人房间 和 1、2、3 三人房间

updateLoacalVideo muted：true或者publish：false remote端的挂载video的dom下的video元素会被remove  updateLoacalVideo muted：false或者publish：true恢复后 remote控制台是接收到对应的事件的但是 挂载video的dom下video元素还是不存在
无法自行恢复

只能在 remote端 监听
 REMOTE_VIDEO_UNAVAILABLE 事件  调用 stopRemoteVideo 和
 REMOTE_VIDEO_AVAILABLE 事件  调用 startRemoteVideo

**Comment by Rychou** [comment]
@JeffesJiang 你好，这个现象是符合预期的。

你那边简单处理只需要在 REMOTE_VIDEO_AVAILABLE 调用 startRemoteVideo 即可，REMOTE_VIDEO_UNAVAILABLE 里可以不调用 stopRemoteVideo

**Comment by JeffesJiang** [comment]
> @JeffesJiang 你好，这个现象是符合预期的。
> 
> 你那边简单处理只需要在 REMOTE_VIDEO_AVAILABLE 调用 startRemoteVideo 即可，REMOTE_VIDEO_UNAVAILABLE 里可以不调用 stopRemoteVideo

在 REMOTE_VIDEO_AVAILABLE 中调用 startRemoteVideo 第二次就会报错，会提示已存在在，所以还是会需要调用stopRemoteVideo

**Comment by Rychou** [comment]
> > @JeffesJiang 你好，这个现象是符合预期的。
> > 你那边简单处理只需要在 REMOTE_VIDEO_AVAILABLE 调用 startRemoteVideo 即可，REMOTE_VIDEO_UNAVAILABLE 里可以不调用 stopRemoteVideo
> 
> 在 REMOTE_VIDEO_AVAILABLE 中调用 startRemoteVideo 第二次就会报错，会提示已存在在，所以还是会需要调用stopRemoteVideo

那是在远端没有取消推流的情况下，重复调用 startRemoteVideo 了吧，如果远端取消推流了，sdk 会自动 stopRemoteVideo。业务侧只需要再下一次 REMOTE_VIDEO_AVAILABLE 时调用 startRemoteVideo 即可
