### ISSUE TITLE
是否支持多端语音通话，仅有一端发布视频流，其余可以观看该直播和语音连麦。

### ISSUE THREAD

**Issue by HHL030303** [LiteAVSDK/TRTC_Web#99]
请问下这个业务场景支持吗？主播发布视频和音频，其余观众可以看到该视频并且观众和主播之间都是可以正常交流，但是观众都不需要推流（开视频）
这个场景支持吗？

**Comment by Rychou** [comment]
支持的，进房的时候可以选择观众角色。

参考：https://web.sdk.qcloud.com/trtc/webrtc/v5/doc/zh-cn/tutorial-12-basic-live-video.html
